[package]
name = "ml-kem"
version = "0.1.0"
edition = "2021"

[dependencies]
polynomial-ring = "0.5.0"
ntt = "0.1.9"
rs_sha3_256 = "0.1.2"
rs_sha3_512 = "0.1.2"
rs_shake128 = "0.1.2"
rs_shake256 = "0.1.2"
aes_ctr_drbg = "0.0.2"
getrandom = "0.2"
num-bigint = "0.4"
num-traits = "0.2"