[package]
name = "ml-kem"
version = "0.1.0"
edition = "2021"

[dependencies]
polynomial-ring = "0.5.0"
module-lwe = "0.1.4"
ring-lwe = "0.1.7"
ntt = "0.1.9"
rs_sha3_256 = "0.1.2"
rs_sha3_512 = "0.1.2"
rs_shake128 = "0.1.2"
rs_shake256 = "0.1.2"
aes_ctr_drbg = "0.0.2"